/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-11-23 05:45:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.commons;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!-- 页面顶部-->\n");
      out.write("<header id=\"top\">\n");
      out.write("\t<div id=\"logo\" class=\"lf\">\n");
      out.write("\t\t<a href=\"/index.html\"> <img\tsrc=\"/images/server/images/portal/header/logo.png\" alt=\"logo\" />\n");
      out.write("\t\t</a>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"top_input\" class=\"lf\">\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t   <div class=\"seek\" tabindex=\"-1\">\n");
      out.write("            <div class=\"actived\" ><span>分类搜索</span> <img src=\"/images/server/images/portal/header/header_normal.png\" alt=\"\"/></div>\n");
      out.write("            <div class=\"seek_content\" >\n");
      out.write("                <div id=\"shcy\" >生活餐饮</div>\n");
      out.write("                <div id=\"xxyp\" >学习用品</div>\n");
      out.write("                <div id=\"srdz\" >私人订制</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"rt\" onclick=\"search1()\"><img id=\"search\"\n");
      out.write("\t\t\tsrc=\"/images/server/images/portal/header/search.png\" alt=\"搜索\"/></a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"rt\">\n");
      out.write("\t\t<ul class=\"lf\" id=\"iul\">\n");
      out.write("\t\t\t<li><a href=\"/collect/toMyCollect.html\" title=\"我的收藏\"> <img class=\"care\"\n");
      out.write("\t\t\t\t\tsrc=\"/images/server/images/portal/header/care.png\"\n");
      out.write("\t\t\t\t\talt=\"\" />\n");
      out.write("\t\t\t</a><b>|</b></li>\n");
      out.write("\t\t\t<li><a href=\"/order/toMyOrder.html\" title=\"我的订单\"> <img class=\"order\"\n");
      out.write("\t\t\t\t\tsrc=\"/images/server/images/portal/header/order.png\" alt=\"\" />\n");
      out.write("\t\t\t</a><b>|</b></li>\n");
      out.write("\t\t\t<li><a href=\"/cart/toCart.html\" title=\"我的购物车\"> <img class=\"shopcar\"\n");
      out.write("\t\t\t\t\tsrc=\"/images/server/images/portal/header/shop_car.png\" alt=\"\" />\n");
      out.write("\t\t\t</a><b>|</b></li>\n");
      out.write("\t\t\t<li><a href=\"/lookforward.html\">帮助</a>\n");
      out.write("\t\t\t<b>|</b></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<br />\n");
      out.write("</header>\n");
      out.write("\t<nav id=\"nav\">\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li><a href=\"/index.html\">首页</a></li>\n");
      out.write("\t\t\t<li><a href=\"/food/toItemFood.html\">生活餐饮</a></li>\n");
      out.write("\t\t\t<li><a href=\"/toCate.html\">学习用品</a></li>\n");
      out.write("\t\t\t<li><a href=\"/lookforward.html\">私人定制</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</nav>\n");
      out.write("\t<script src=\"/js/jquery-3.1.1.min.js\"></script>\n");
      out.write("\t<script src=\"/js/slide.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tfunction logout() {\n");
      out.write("\t\t\tvar ticket = $.cookie(\"DN_TICKET\");\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl : 'http://localhost:18888/logout/'+ticket+'.html',\n");
      out.write("\t\t\t\ttype : 'post',\n");
      out.write("\t\t\t\tdataType:'json',\n");
      out.write("\t\t\t\tsuccess:function(result) {\n");
      out.write("\t\t\t\t\tif (result != null && result != \"\" && result != undefined) {\n");
      out.write("\t\t\t\t\t\tif (result.status == 200) {\n");
      out.write("\t\t\t\t\t\t\talert(result.msg);\n");
      out.write("\t\t\t\t\t\t\twindow.location.href = \"http://localhost:18882/sso/toLogin.html\";\n");
      out.write("\t\t\t\t\t\t}else {\n");
      out.write("\t\t\t\t\t\t\talert(result.msg);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function() {\n");
      out.write("\t\t\t\t\talert('退出失败！');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t<script>\n");
      out.write("\t$('#nav>ul>li').click(function(){\n");
      out.write("        $(this).children().addClass('active');\n");
      out.write("        $(this).siblings().children().removeClass('active');\n");
      out.write("    })\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"/js/jquery.cookie.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(function () {\n");
      out.write("\t\t\t//请求本网站checkLogin.html,checkLogin()用httpClient做代理去访问sso\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype:\"POST\",\n");
      out.write("\t\t\t\turl:\"/user/checkLogin.html\",\n");
      out.write("\t\t\t\txhrFields:{withCredentials:true},\n");
      out.write("\t\t\t\tdataType:\"json\",\n");
      out.write("\t\t\t\tsuccess:function(result){\n");
      out.write("\t\t\t\t\tvar user = result.data;\n");
      out.write("\t\t\t\t\tconsole.log(result);\n");
      out.write("\t\t\t\t\tif (result.status === 200) {\n");
      out.write("\t\t\t\t\t\t$(\"#iul\").append('<li><a href=\"/lookforward.html\">'+user.username+'</a><b>|</b></li><li><a href=\"javascript:;\" onclick=\"logout()\">退出</a></li>');\n");
      out.write("\t\t\t\t\t}else if(result.status === 500){\n");
      out.write("\t\t\t\t\t\t$(\"#iul\").append('<li><a href=\"http://sso.ajstore.com:90/user/toLogin.html?callback=http://www.ajstore.com\">登录</a></li>');\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(textStatus,XMLHttpRequest){\n");
      out.write("\t\t\t\t\t//alert(\"系统异常！\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t//$.cookie出异常\n");
      out.write("\t\t\t//var ticket = $.cookie(\"DN_TICKET\");\n");
      out.write("\t\t\t//服务器返回的是js,这种处理跨域的方式叫jsonp\n");
      out.write("\t\t\t/* $.ajax({\n");
      out.write("\t\t\t\ttype:\"post\",\n");
      out.write("\t\t\t\turl:\"http://sso.ajstore.com:90/user/checkLoginForJsonp.html\",\n");
      out.write("\t\t\t\tdataType:\"jsonp\",\n");
      out.write("\t\t\t\tjsonp:\"jsonpCallback\",//jsonpCallback是服务器端接收参数的参数名\n");
      out.write("\t\t\t\txhrFields:{withCredentials:true},//ajax默认不发送cookie\n");
      out.write("\t\t\t\t//浏览器收到的是jquery(json字符串)\n");
      out.write("\t\t\t\t//函数名jquery\n");
      out.write("\t\t\t\t//执行函数jquery,得到的是json字符串，再调用success,把json字符串传过来了\n");
      out.write("\t\t\t\tsuccess:function(result){\n");
      out.write("\t\t\t\t\tvar user = result.data;\n");
      out.write("\t\t\t\t\tconsole.log(result);\n");
      out.write("\t\t\t\t\tif (result.status === 200) {\n");
      out.write("\t\t\t\t\t\t$(\"#iul\").append('<li><a href=\"/lookforward.html\">'+user.username+'</a><b>|</b></li><li><a href=\"javascript:;\" onclick=\"logout()\">退出</a></li>');\n");
      out.write("\t\t\t\t\t}else if(result.status === 500){\n");
      out.write("\t\t\t\t\t\t$(\"#iul\").append('<li><a href=\"http://sso.ajstore.com:90/user/toLogin.html?callback=http://www.ajstore.com\">登录</a></li>');\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(textStatus,XMLHttpRequest){\n");
      out.write("\t\t\t\t\talert(\"系统异常！\"+JSON.stringify(textStatus)+\" ------ \"+XMLHttpRequest);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}); */\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//服务器返回的是json\n");
      out.write("\t\t\t/* $.ajax({\n");
      out.write("\t\t\t\ttype:\"post\",\n");
      out.write("\t\t\t\turl:\"http://sso.ajstore.com:90/user/checkLogin.html\",\n");
      out.write("\t\t\t\tdataType:\"json\",//原先是jsonp要改成json\n");
      out.write("\t\t\t\txhrFields:{withCredentials:true},//ajax默认不发送cookie\n");
      out.write("\t\t\t\tsuccess:function(result){\n");
      out.write("\t\t\t\t\tvar user = result.data;\n");
      out.write("\t\t\t\t\tconsole.log(result);\n");
      out.write("\t\t\t\t\tif (result.status === 200) {\n");
      out.write("\t\t\t\t\t\t$(\"#iul\").append('<li><a href=\"/lookforward.html\">'+user.username+'</a><b>|</b></li><li><a href=\"javascript:;\" onclick=\"logout()\">退出</a></li>');\n");
      out.write("\t\t\t\t\t}else if(result.status === 500){\n");
      out.write("\t\t\t\t\t\t$(\"#iul\").append('<li><a href=\"http://sso.ajstore.com:90/user/toLogin.html?callback=http://www.ajstore.com\">登录</a></li>');\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(textStatus,XMLHttpRequest){\n");
      out.write("\t\t\t\t\talert(\"系统异常！\"+JSON.stringify(textStatus)+\" ------ \"+XMLHttpRequest);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}); */\n");
      out.write("\t\t})\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("function search1(){\n");
      out.write("\tvar q=$(\"#input\").val();\n");
      out.write("\tconsole.log(q);\n");
      out.write("\twindow.location.href = \"/search/toSearch.html?key=\"+q;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">   \n");
      out.write("\n");
      out.write("    document.onkeydown=keyDownSearch;\n");
      out.write("   \n");
      out.write("    function keyDownSearch(e) { \n");
      out.write("        var theEvent = e || window.event; \n");
      out.write("        var code = theEvent.keyCode || theEvent.which || theEvent.charCode; \n");
      out.write("        if (code == 13) {  \n");
      out.write("        \tsearch1();\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("        return true;\n");
      out.write("    }\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/commons/header.jsp(12,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(false);
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t<input id=\"input\" type=\"text\" placeholder=\"${q}\" />\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t<input id=\"input\" type=\"text\" placeholder=\"请输入您要搜索的内容\" />\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
