//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : jt
//  @ File Name : SearchService.java
//  @ Date : 2018/11/28
//  @ Author : 
//
//



package com.jt.search.Service;

import java.util.List;
//=========SearchService============
public class SearchService {
	public List search(String key) {
	return null;
	}
}
